install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/app/libMVM.dll"
        DESTINATION "${CMAKE_INSTALL_PREFIX}"
        COMPONENT Runtime)

set(APP_BIN_DIR "${CMAKE_INSTALL_PREFIX}/bin")

install(PROGRAMS "${CMAKE_CURRENT_SOURCE_DIR}/app/MVMVpnCore.exe"
        DESTINATION "${APP_BIN_DIR}")
install(FILES "${CMAKE_CURRENT_SOURCE_DIR}/app/wintun.dll"
        DESTINATION "${APP_BIN_DIR}"
        COMPONENT Runtime)
