PROJECT_CONFIG = {
    "MVMVpn": {
        "build_number.base": 300,
        "core.dir": "libMVM",
        "core.lib.src.files.ios": ["LibMVM.xcframework"],
        "core.lib.src.files.macos": ["LibMVM.xcframework"],
        "core.lib.src.files.android": ["libMVM-sources.jar", "libMVM.aar"],
        "core.lib.src.files.linux": ["linux_so/libMVM.so"],
        "core.lib.src.files.windows": ["windows_dll/libMVM.dll"],
        "core.lib.dst.dir.ios": "../swift/all",
        "core.lib.dst.dir.macos": "../swift/all",
        "core.lib.dst.dir.android": "app/libs",
        "core.lib.dst.dir.linux": "app",
        "core.lib.dst.dir.windows": "app",
        "core.dat.dst.dir": "../assets/dat",
        "core.bin.src.file.linux": "bin/xray",
        "core.bin.dst.file.linux": "app/MVMVpnCore",
        "core.bin.src.file.windows": "bin/xray.exe",
        "core.bin.dst.file.windows": "app/MVMVpnCore.exe",
        "app.release.dir.android": "../build/app/outputs",
        "app.release.dir.linux": "../dist",
        "app.release.dir.windows": "../dist",
    },
}
