name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Run Deploy Script
        run: |
          chmod +x backend/deploy.sh
          ./backend/deploy.sh
        env:
          SSH_PASSWORD: "zgtejT3R7v0u"
